config/routes.rb
Storyline::Application.routes.draw do
  devise_for :users
  root 'static#home'
  get 'ui(/:action)', controller: 'ui'
  get 'about' => 'static#about'
  get 'home' => 'static#home'

  resources :stories, only: [:new, :create, :show, :index] do
    resources :entries, only: [:create]
  end

  resource :unfinished_story, only: [:show]
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  validates :body, length: {minimum: 3, maximum: 150}

  def self.previous_by_users_other_than(user)
    where(id: Entry.select("max(entries.id)").group(:story_id)).where.not(user: user)
  end

  def author
    self.author_name || self.user.username
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :entries
  belongs_to :user
  validates :title, presence: true, length: {maximum: 50}
  validates :first_entry, length: {minimum: 3, maximum: 150}

  def self.finished_stories
    # joins(:entries).group("stories.id").having("count(entries.id) >= 5")
    where(finished: true)
  end

  def self.unfinished
    # joins('LEFT JOIN entries ON stories.id = entries.story_id').group("stories.id").having("count(entries.id) < 5")
    where(finished: false)
  end

  def self.unstarted
    includes(:entries).where(:entries => {id: nil})
  end

  def self.for_users_other_than(user)
    where.not(user: user)
  end

  def self.for_prev_entries_not_by(user)
    where(id: Entry.previous_by_users_other_than(user).pluck(:story_id))
  end

  def previous_entry
    if self.entries.size == 0
      self.first_entry
    else
      self.entries.last.body
    end
  end

  def author
    self.author_name || self.user.username
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stories
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @story.finished = true if params[:story_status] == '1'

    @entry = Entry.new(entry_params)
    @entry.user_id = current_user.id if user_signed_in?

    if @entry.save
      @story.save #save in case status changed
      flash[:success] = 'Your entry was saved. Write another!'
      redirect_to unfinished_story_path
    else
      flash[:alert] = 'Hmmm... Something went wrong. Your entry was not saved.'
      render 'stories/show'
    end
  end

  private
  def entry_params
    params.require(:entry).permit(:body, :story_id, :author_name)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end

  def about
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.finished_stories
  end

  def show
    @story = Story.find(params[:id])

    if @story.finished?
      redirect_to stories_path
    else
      @entry = Entry.new
    end
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user_id = current_user.id if user_signed_in?

    if @story.save
      flash[:success] = 'Your story was successfully saved'
      redirect_to :root
    else
      flash[:error] = 'Something went wrong and your story was NOT saved!'
      render :new
    end
  end

  private
  def story_params
    params.require(:story).permit(:title, :first_entry, :author_name)
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_action do
    redirect_to :root if Rails.env.production?
  end
    
  def index
    pages = Dir.glob 'app/views/ui/*'
    @mock_views = pages.map do |filename|
      file = File.basename(filename, '.html.haml')
    end
  end
end

app/controllers/unfinished_stories_controller.rb
class UnfinishedStoriesController < ApplicationController
  def show
    if user_signed_in?
      random_story = Story.for_users_other_than(current_user).unstarted.sample || Story.for_prev_entries_not_by(current_user).unfinished.sample 
    else
      random_story = Story.unfinished.sample
    end

    if random_story.nil?
      flash[:notice] = "Sorry, no unfinished stories to add to right now. Would you like to start a new one?"
      redirect_to new_story_path
    else
      redirect_to random_story
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_message.html.haml
- flash.each do |type, msg|
  - if type == :alert || type == :error
    .notice.alert.alert-danger= msg
  - elsif type == :success || type == :notice
    .notice.alert.alert-success= msg

app/views/layouts/_navbar.html.haml
.navbar.navbar-default#top-header
  .container
    .navbar-text.pull-right
      - if user_signed_in?
        #login-info= "Currently logged in as #{current_user.username}"
        %br
        = link_to 'Log Out', destroy_user_session_path, class: 'btn btn-default', method: 'delete'
      - else
        = link_to 'Log In', new_user_session_path, class: 'btn btn-default'
        = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary'
    %h1= link_to 'StoryLines', root_path
    %ul.nav.navbar-nav.text-center
      %li= link_to "Home", home_path
      %li
        = link_to new_story_path do
          %span.glyphicon.glyphicon-plus
          New Story
      %li
        = link_to unfinished_story_path do
          %span.glyphicon.glyphicon-edit
          Continue Story
      %li
        = link_to 'Read Stories', stories_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Storylines
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cabin+Sketch'
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = csrf_meta_tags 

  %body
    %header
      = render 'layouts/navbar'
    %section.content.clearfix
      .container
        = render 'layouts/message'
        = yield
    %footer

app/views/shared/_errors.html.haml
.alert.alert-danger
  %ul 
    - obj.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_header.html.haml
%h1{style: 'text-align: center'}= header_title
%hr

app/views/stories/index.html.haml
= render 'shared/header', header_title: 'Finished Stories'

- if @stories.empty?
  %p Sorry, there are no finished stories yet!

.container
  - @stories.each do |story|
    .well
      .row
        .col-md-11.col-md-offset-1
          %h3= story.title
        .col-md-7.col-lg-7.col-md-offset-1.col-lg-offset-1
          = story.first_entry
          %sup 1
          - story.entries.each_with_index do |entry, index|
            = entry.body
            %sup= "#{index + 2}" 
        .col-md-3.col-md-offset-1
          %h4 Authors
          %ol
            %li= story.author
            - story.entries.each do |entry|
              %li= entry.author

app/views/stories/new.html.haml
- if @story.errors.any?
  = render 'shared/errors', obj: @story 
  
=render 'shared/header', header_title: 'Start a New Story'

= form_for @story do |f|
  = f.label :title, "What is your story called?"
  %br
  = f.text_field :title, {size: 50}
  %br
  %br
  = f.label :first_entry, "How does it begin?"
  %br
  = f.text_area :first_entry, {size: '50x5', maxlength: 140}
  %br
  - unless user_signed_in?
    = f.label :author_name, "What's your pen name?"
    %br
    = f.text_field :author_name
    %br
  %br
  = f.submit "Start Story", class: 'btn btn-primary'

app/views/stories/show.html.haml
= render 'shared/header', header_title: 'Continue Story'

- if @entry.errors.any?
  = render 'shared/errors', obj: @entry


%h2= @story.title
%p= @story.previous_entry

= form_for [@story, @entry] do |f|
  = f.hidden_field :story_id, value: @story.id
  %br
  = f.label :body, 'What happens next?'
  %br
  = f.text_area :body
  %br
  - unless user_signed_in?
    = f.label :author_name, "What's your pen name?"
    %br
    = f.text_field :author_name
    %br
  = check_box_tag :story_status
  = label_tag :story_status, 'Finish this story'
  %br
  = f.submit 'Add your line', class: 'btn btn-primary'

app/views/ui/about.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %p 
        %em Remember that game we played as kids where everybody would start a story on a piece of paper, then pass around the papers and continue each others' stories? (No? Just me?) Well anyway, this is that game. Enjoy :)

  .row
    = render 'shared/header', header_title: 'How It Works'
  .row
    .col-md-3.col-md-offset-2
      %h4 Someone starts a story, giving it a title and a few lines. Just enough to get the ball rolling...
    .col-md-4
      .well
        %h3 The Curious Cat
        %p One day, Chester the Cat was playing around in the bushes when all of the sudden he saw a giant mouse!
 
  %br
  %br

  .row
    .col-md-4
      .well
        %h3 The Curious Cat
        %p Since he had never seen a mouse, the cat tried to touch it with his paw.
        %p
          %strong What comes next?
          .well{style: 'background-color: white'} 
            %p Unfortunately, mice don't like being touched, let's just say that kitty only has 3 paws now.
    .col-md-3
      %h4 Then other people continue the story by adding one new line at a time. The catch is they only get to see the title and the previous line that was written. Let chaos ensue!
  
  %br
  %br

  .row
    .col-md-2.col-md-offset-3
      %h4 After 6 lines have been written, the story is "finished" and everyone gets to read it. 
    .col-md-5 
      .well
        %h3 The Curious Cat
        %p One day, Chester the Cat was playing around in the bushes when all of the sudden he saw a giant mouse! He never saw a mouse before, but was quite curious about it. Since he had never seen a mouse, the cat tried to touch it with his paw. Unfortunately, mice don't like being touched, let's just say that kitty only has 3 paws now. With his new disability, Chester realized that he would have to change many aspects about his life. Chester rapidly became depressed, knowing that all of these life changes would be very difficult, so he began eating too much and died of complications from morbid obesity.

app/views/ui/index.html.haml
= render 'shared/header', header_title: 'Mock Pages'

%h3 Links to static pages:

%ul
  - @mock_views.each do |view|
    %li= link_to view.titleize, action: view

app/views/ui/index_finished_stories.html.haml
= render 'shared/header', header_title: 'Finished Stories'

- entries = ["Once upon a time (yesterday) I went to the park.", "It was bright and sunny out and there were lots of screaming children.", "Of course, I would be screaming too if there was a giant clown chasing me...", "I bet I could outrun anyone there though, so I'm good.", "Especially if there's cake involved!", "Hopefully a cake with a midget popping out!"]
- authors = ['abcMan', 'katy_waty', 'mr_bubbles', 'snickerslvr', 'abcMan', 'Bob']


.container
  -['Yesterday at the Park', 'Holy Cow!', 'Plate of Bacon', 'Mambo Number 6'].each do |title|
    .row
      .col-md-11.col-md-offset-1
        %h3= title
      .col-md-7.col-lg-7.col-md-offset-1.col-lg-offset-1
        - entries.each_with_index do |entry, index|
          = entry
          %sup= "#{index + 1}" 
      .col-md-3.col-md-offset-1
        %ol
          - authors.each do |author|
            %li= author

app/views/ui/new_entry.html.haml
= render 'shared/header', header_title: 'Add a line to...'

.container
  %h3 The Day that Janie Went to Disneyland
  %p "She wanted to go on Mr. Toad's Wild Ride, but it was closed."

  =form_tag({controller: :ui, action: :index}, method: 'get') do
    = label_tag :entry, 'What happens next?'
    = text_area_tag :entry
    %br
    = submit_tag 'Add My Line', class: 'btn btn-primary'

app/views/ui/new_story.html.haml
=render 'shared/header', header_title: 'Start a New Story'

= form_tag({controller: 'ui', action: 'index'}, method: 'get') do
  = label_tag :title, "What is your story called?"
  %br
  = text_field_tag :title, '', size: 50
  %br
  %br
  = label_tag :entry, "How does it begin?"
  %br
  = text_area_tag :entry, '', size: '50x5', maxlength: 140
  %br
  %br
  = submit_tag "Start Story", class: 'btn btn-primary'